// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "fa2563008eb256150ae2917564a2a1e87e18150c51967745af27afec5c42e19d")
