// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "bff40bef4b899cb0e39f041206a4015e9c96b6de567a6eb0347cc3e837a61ede")
